const seed=[
{id:1,n:"Smartphone Nova X",p:85000,c:"Téléphones",img:"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900",d:"Smartphone moderne, rapide et élégant."},
{id:2,n:"Sneakers Urban",p:25000,c:"Chaussures",img:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900",d:"Chaussures confortables pour le quotidien."},
{id:3,n:"Casque Bluetooth Pro",p:18000,c:"Audio",img:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900",d:"Son immersif et connexion sans fil."},
{id:4,n:"Sac Premium",p:15000,c:"Mode",img:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=900",d:"Sac pratique et résistant."},
{id:5,n:"Montre Connectée",p:30000,c:"Accessoires",img:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900",d:"Design moderne et fonctions connectées."},
{id:6,n:"T-shirt Premium",p:12000,c:"Mode",img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900",d:"T-shirt confortable au style moderne."}];
let products=JSON.parse(localStorage.getItem("sm_products")||"null")||seed,cart=JSON.parse(localStorage.getItem("sm_cart")||"[]"),orders=JSON.parse(localStorage.getItem("sm_orders")||"[]");
const money=n=>new Intl.NumberFormat("fr-FR").format(n)+" FCFA",save=()=>{localStorage.sm_products=JSON.stringify(products);localStorage.sm_cart=JSON.stringify(cart);localStorage.sm_orders=JSON.stringify(orders)};
function go(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");render();scrollTo(0,0)}
function card(x){return `<article class="product"><img src="${x.img}" onerror="this.src='https://placehold.co/600x400?text=Produit'"><div class="body"><span class="muted">${x.c}</span><h3>${x.n}</h3><div class="price">${money(x.p)}</div><button class="cta" onclick="detail(${x.id})">Voir le produit</button></div></article>`}
function detail(id){let x=products.find(p=>p.id===id);document.getElementById("detailBox").innerHTML=`<div class="productDetail"><img src="${x.img}"><div><span class="muted">${x.c}</span><h1>${x.n}</h1><div class="bigPrice">${money(x.p)}</div><p>${x.d}</p><button class="cta" onclick="add(${x.id})">Ajouter au panier</button></div></div>`;go("detail")}
function add(id){let x=cart.find(a=>a.id===id);x?x.q++:cart.push({id,q:1});save();badge();alert("Produit ajouté au panier.");}
function badge(){badgeEl=document.getElementById("badge");badgeEl.textContent=cart.reduce((a,x)=>a+x.q,0)}
function render(){let cats=[...new Set(products.map(x=>x.c))],cat=document.getElementById("cat"),q=(document.getElementById("q")?.value||"").toLowerCase();if(cat)cat.innerHTML='<option value="all">Toutes les catégories</option>'+cats.map(x=>`<option value="${x}">${x}</option>`).join("");document.getElementById("cats").innerHTML=cats.map(x=>`<button class="cat" onclick="document.getElementById('cat').value='${x}';go('shop')">🛍️<br>${x}</button>`).join("");let arr=products.filter(x=>(!q||x.n.toLowerCase().includes(q)||x.c.toLowerCase().includes(q))&&(!cat||cat.value==="all"||x.c===cat.value));let sort=document.getElementById("sort")?.value;if(sort==="priceUp")arr.sort((a,b)=>a.p-b.p);if(sort==="priceDown")arr.sort((a,b)=>b.p-a.p);document.getElementById("featured").innerHTML=products.slice(0,4).map(card).join("");document.getElementById("list").innerHTML=arr.map(card).join("");cartRender();ordersRender();sellerRender();badge()}
function cartRender(){let b=document.getElementById("cartBox");if(!cart.length){b.innerHTML="<div class='panel'>Ton panier est vide.</div>";return}let total=0;b.innerHTML=cart.map(i=>{let x=products.find(p=>p.id===i.id);total+=x.p*i.q;return `<div class="cartItem"><span><b>${x.n}</b><br><small>${i.q} × ${money(x.p)}</small></span><button onclick="removeItem(${x.id})">Supprimer</button></div>`}).join("")+`<div class="total"><h2>${money(total)}</h2><button class="cta" onclick="checkout()">Commander</button></div>`}
function removeItem(id){cart=cart.filter(x=>x.id!==id);save();render()}
function checkout(){if(!cart.length)return;let total=cart.reduce((s,i)=>s+products.find(x=>x.id===i.id).p*i.q,0);orders.unshift({id:Date.now(),total,status:"En préparation"});cart=[];save();go("orders");alert("Commande enregistrée.");}
function ordersRender(){let b=document.getElementById("orderBox");b.innerHTML=orders.length?orders.map(o=>`<div class="panel" style="margin:10px 0"><b>Commande #${String(o.id).slice(-6)}</b><p>${money(o.total)} • ${o.status}</p></div>`).join(""):"<div class='panel'>Aucune commande pour le moment.</div>"}
function saveUser(){localStorage.sm_user=JSON.stringify({n:document.getElementById("name").value,p:document.getElementById("phone").value});alert("Profil enregistré.")}
function addProduct(){let n=pn.value,p=Number(pp.value),c=pc.value||"Autre",img=pi.value||"https://placehold.co/700x500?text=Produit",d=pd.value||"Produit disponible.";if(!n||!p)return alert("Nom et prix obligatoires.");products.unshift({id:Date.now(),n,p,c,img,d});save();render();alert("Produit publié.")}
function sellerRender(){sProducts.textContent=products.length;sOrders.textContent=orders.length;sSales.textContent=money(orders.reduce((a,x)=>a+x.total,0));sellerProducts.innerHTML=products.slice(0,8).map(x=>`<p><b>${x.n}</b> — ${money(x.p)}</p>`).join("")}
render();badge();