const express=require('express'),path=require('path'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),db=require('./db');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'dev-only-change-this-secret';
if(process.env.NODE_ENV==='production' && SECRET==='dev-only-change-this-secret') throw new Error('JWT_SECRET doit être défini en production');
app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
const sign=u=>jwt.sign({id:u.id,email:u.email,role:u.role,name:u.name},SECRET,{expiresIn:'7d'});
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:'Connexion requise'})}}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Accès refusé'})}
app.get('/api/health',(req,res)=>res.json({ok:true,app:'SENMARKET PRO',version:'2.0.0'}));
app.get('/api/products',(req,res)=>{const q=String(req.query.q||'').trim();const cat=String(req.query.category||'').trim();let sql='SELECT * FROM products WHERE active=1',args=[];if(q){sql+=' AND (name LIKE ? OR category LIKE ?)';args.push('%'+q+'%','%'+q+'%')}if(cat){sql+=' AND category=?';args.push(cat)}sql+=' ORDER BY id DESC';res.json(db.prepare(sql).all(...args))});
app.get('/api/categories',(req,res)=>res.json(db.prepare('SELECT DISTINCT category FROM products WHERE active=1 ORDER BY category').all().map(x=>x.category)));
app.post('/api/register',(req,res)=>{const {name,email,password,phone}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Nom, email et mot de passe (6 caractères minimum) requis'});try{const hash=bcrypt.hashSync(password,10);const r=db.prepare('INSERT INTO users(name,email,password,phone,role) VALUES(?,?,?,?,?)').run(name,email.toLowerCase(),hash,phone||'', 'customer');const u={id:r.lastInsertRowid,name,email:email.toLowerCase(),role:'customer'};res.json({token:sign(u),user:u})}catch(e){res.status(400).json({error:'Cet email est déjà utilisé'})}});
app.post('/api/login',(req,res)=>{const email=String(req.body.email||'').toLowerCase();const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!bcrypt.compareSync(req.body.password||'',u.password))return res.status(401).json({error:'Identifiants incorrects'});res.json({token:sign(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,phone:u.phone}})});
app.get('/api/me',auth,(req,res)=>res.json(db.prepare('SELECT id,name,email,role,phone,created_at FROM users WHERE id=?').get(req.user.id)));
app.post('/api/products',auth,role('seller','admin'),(req,res)=>{const {name,price,category,image,description,stock}=req.body;if(!name||!Number.isFinite(Number(price))||Number(price)<0)return res.status(400).json({error:'Nom et prix valides requis'});const r=db.prepare('INSERT INTO products(name,price,category,image,description,seller_id,stock) VALUES(?,?,?,?,?,?,?)').run(name,Number(price),category||'Autre',image||'',description||'',req.user.id,Math.max(0,Number(stock)||0));res.json(db.prepare('SELECT * FROM products WHERE id=?').get(r.lastInsertRowid))});
app.put('/api/products/:id',auth,role('seller','admin'),(req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'Produit introuvable'});if(req.user.role==='seller'&&p.seller_id!==req.user.id)return res.status(403).json({error:'Ce produit ne vous appartient pas'});const x=req.body;db.prepare('UPDATE products SET name=?,price=?,category=?,image=?,description=?,stock=?,active=? WHERE id=?').run(x.name??p.name,Number(x.price??p.price),x.category??p.category,x.image??p.image,x.description??p.description,Number(x.stock??p.stock),x.active===undefined?p.active:Number(x.active),p.id);res.json(db.prepare('SELECT * FROM products WHERE id=?').get(p.id))});
app.delete('/api/products/:id',auth,role('seller','admin'),(req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'Produit introuvable'});if(req.user.role==='seller'&&p.seller_id!==req.user.id)return res.status(403).json({error:'Accès refusé'});db.prepare('UPDATE products SET active=0 WHERE id=?').run(p.id);res.json({ok:true})});
app.post('/api/orders',auth,(req,res)=>{const {items,payment_method,address,phone}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({error:'Panier vide'});let total=0,lines=[];for(const i of items){const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(Number(i.id));const qty=Math.max(1,Number(i.qty)||1);if(!p)return res.status(400).json({error:'Produit introuvable'});if(p.stock<qty)return res.status(400).json({error:`Stock insuffisant : ${p.name}`});total+=p.price*qty;lines.push({p,qty})}const tx=db.transaction(()=>{const r=db.prepare('INSERT INTO orders(user_id,total,status,payment_method,payment_status,address,phone) VALUES(?,?,?,?,?,?,?)').run(req.user.id,total,'En préparation',payment_method||'À la livraison',payment_method&&payment_method!=='À la livraison'?'À payer':'À la livraison',address||'',phone||'');const ins=db.prepare('INSERT INTO order_items(order_id,product_id,qty,price) VALUES(?,?,?,?)');const dec=db.prepare('UPDATE products SET stock=stock-? WHERE id=?');lines.forEach(x=>{ins.run(r.lastInsertRowid,x.p.id,x.qty,x.p.price);dec.run(x.qty,x.p.id)});return r.lastInsertRowid});const id=tx();res.status(201).json(db.prepare('SELECT * FROM orders WHERE id=?').get(id))});
app.get('/api/orders',auth,(req,res)=>res.json(db.prepare(`SELECT o.*,GROUP_CONCAT(p.name||' x'||oi.qty, ', ') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id LEFT JOIN products p ON p.id=oi.product_id WHERE o.user_id=? GROUP BY o.id ORDER BY o.id DESC`).all(req.user.id)));
app.get('/api/seller/orders',auth,role('seller','admin'),(req,res)=>res.json(db.prepare(`SELECT DISTINCT o.*,u.name customer,u.email FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id JOIN users u ON u.id=o.user_id WHERE ?='admin' OR p.seller_id=? ORDER BY o.id DESC`).all(req.user.role,req.user.id)));
app.patch('/api/orders/:id/status',auth,role('seller','admin'),(req,res)=>{const allowed=['En préparation','Expédiée','Livrée','Annulée'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Statut invalide'});const o=db.prepare('SELECT * FROM orders WHERE id=?').get(req.params.id);if(!o)return res.status(404).json({error:'Commande introuvable'});db.prepare('UPDATE orders SET status=? WHERE id=?').run(req.body.status,o.id);res.json({ok:true})});
app.get('/api/admin/stats',auth,role('admin'),(req,res)=>res.json({users:db.prepare('SELECT COUNT(*) c FROM users').get().c,products:db.prepare('SELECT COUNT(*) c FROM products WHERE active=1').get().c,orders:db.prepare('SELECT COUNT(*) c FROM orders').get().c,revenue:db.prepare("SELECT COALESCE(SUM(total),0) n FROM orders WHERE status!='Annulée'").get().n}));
app.post('/api/admin/promote',auth,role('admin'),(req,res)=>{const u=db.prepare('SELECT id FROM users WHERE email=?').get(String(req.body.email||'').toLowerCase());if(!u)return res.status(404).json({error:'Utilisateur introuvable'});const role=req.body.role==='admin'?'admin':'seller';db.prepare('UPDATE users SET role=? WHERE id=?').run(role,u.id);res.json({ok:true,role})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));
app.listen(PORT,()=>console.log(`SENMARKET PRO http://localhost:${PORT}`));
